In [1]:
print('test')

test


In [2]:
import numpy as np

In [ ]:
# Numpy bizim bir veya cok boyutlu liste tiplerinde (numpy ismiyle arrayler ile) kapsamli bir seklide islem yapmamiza yarar.

In [5]:
array1 = np.array([1,2,3,4])
print(f"array1: {array1}")

print(array1.ndim)  # boyutu
print(array1.shape) # sekli
print(array1.size)  # size
print(array1.dtype)  # tipi

array1: [1 2 3 4]
1
(4,)
4
int64


In [ ]:
array1 = np.array([[1,2,3,4],[5,6,7,8]])    # bu matris oldu
print(f"array1: {array1}")

print(array1.ndim)  # boyutu
print(array1.shape) # sekli
print(array1.size)  # size
print(array1.dtype)  # tipi

array1: [[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
8
int64


In [ ]:
array1 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])     # bu da 3 boutlu
print(f"array1: \n{array1}")

print(array1.ndim)  # boyutu
print(array1.shape) # sekli
print(array1.size)  # size
print(array1.dtype)  # tipi

array1: 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
(2, 2, 4)
16
int64
